// Official USCIS 128 Civics Questions for the 2025 Naturalization Test
// Effective for N-400 applications filed on or after October 20, 2025
// Source: https://www.uscis.gov/citizenship-resource-center/naturalization-test-and-study-resources/2025-civics-test
// Format: 20 questions asked, 12 correct needed to pass

export const CIVICS_QUESTIONS = [
  // === AMERICAN GOVERNMENT ===
  // A: Principles of American Government (Q1-15)
  { number: 1, question_en: "What is the form of government of the United States?", answer_en: "Republic; Constitution-based federal republic; Representative democracy", answer_en_alt: ["Republic", "Constitution-based federal republic", "Representative democracy"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 2, question_en: "What is the supreme law of the land?", answer_en: "The U.S. Constitution", answer_en_alt: ["the Constitution", "U.S. Constitution"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 3, question_en: "Name one thing the U.S. Constitution does.", answer_en: "Forms the government; Defines powers of government; Defines the parts of government; Protects the rights of the people", answer_en_alt: ["forms the government", "defines powers of government", "defines the parts of government", "protects the rights of the people"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 4, question_en: "The U.S. Constitution starts with the words 'We the People.' What does 'We the People' mean?", answer_en: "Self-government; Popular sovereignty; Consent of the governed; People should govern themselves", answer_en_alt: ["self-government", "popular sovereignty", "consent of the governed", "people should govern themselves"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 5, question_en: "How are changes made to the U.S. Constitution?", answer_en: "Amendments; The amendment process", answer_en_alt: ["amendments", "the amendment process"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 6, question_en: "What does the Bill of Rights protect?", answer_en: "The basic rights of Americans; The basic rights of people living in the United States", answer_en_alt: ["the basic rights of Americans", "the basic rights of people living in the United States"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 7, question_en: "How many amendments does the U.S. Constitution have?", answer_en: "Twenty-seven (27)", answer_en_alt: ["27", "twenty-seven"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 8, question_en: "Why is the Declaration of Independence important?", answer_en: "It says America is free from British control; It says all people are created equal; It identifies inherent rights; It identifies individual freedoms", answer_en_alt: ["it says America is free from British control", "it says all people are created equal", "it identifies inherent rights", "it identifies individual freedoms"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 9, question_en: "What founding document said the American colonies were free from Britain?", answer_en: "Declaration of Independence", answer_en_alt: ["Declaration of Independence"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 10, question_en: "Name two important ideas from the Declaration of Independence and the U.S. Constitution.", answer_en: "Equality; Liberty; Social contract; Natural rights; Limited government; Self-government", answer_en_alt: ["equality", "liberty", "social contract", "natural rights", "limited government", "self-government"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 11, question_en: "The words 'Life, Liberty, and the pursuit of Happiness' are in what founding document?", answer_en: "Declaration of Independence", answer_en_alt: ["Declaration of Independence"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 12, question_en: "What is the economic system of the United States?", answer_en: "Capitalism; Free market economy", answer_en_alt: ["capitalism", "free market economy", "free market", "market economy"], category: "American Government", subcategory: "Principles of American Government", starred: true },
  { number: 13, question_en: "What is the rule of law?", answer_en: "Everyone must follow the law; Leaders must obey the law; Government must obey the law; No one is above the law", answer_en_alt: ["everyone must follow the law", "leaders must obey the law", "government must obey the law", "no one is above the law"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 14, question_en: "Many documents influenced the U.S. Constitution. Name one.", answer_en: "Declaration of Independence; Articles of Confederation; Federalist Papers; Anti-Federalist Papers; Virginia Declaration of Rights; Fundamental Orders of Connecticut; Mayflower Compact; Iroquois Great Law of Peace", answer_en_alt: ["Declaration of Independence", "Articles of Confederation", "Federalist Papers", "Anti-Federalist Papers", "Virginia Declaration of Rights", "Fundamental Orders of Connecticut", "Mayflower Compact", "Iroquois Great Law of Peace"], category: "American Government", subcategory: "Principles of American Government" },
  { number: 15, question_en: "There are three branches of government. Why?", answer_en: "So one part does not become too powerful; Checks and balances; Separation of powers", answer_en_alt: ["so one part does not become too powerful", "checks and balances", "separation of powers"], category: "American Government", subcategory: "Principles of American Government" },

  // B: System of Government (Q16-62)
  // Congress
  { number: 16, question_en: "Name the three branches of government.", answer_en: "Legislative, executive, and judicial", answer_en_alt: ["legislative, executive, and judicial", "Congress, President, and the courts"], category: "American Government", subcategory: "System of Government" },
  { number: 17, question_en: "The President of the United States is in charge of which branch of government?", answer_en: "Executive branch", answer_en_alt: ["executive branch", "the executive branch"], category: "American Government", subcategory: "System of Government" },
  { number: 18, question_en: "What part of the federal government writes laws?", answer_en: "U.S. Congress; Legislature; Legislative branch", answer_en_alt: ["Congress", "U.S. Congress", "legislature", "legislative branch"], category: "American Government", subcategory: "System of Government" },
  { number: 19, question_en: "What are the two parts of the U.S. Congress?", answer_en: "The Senate and House of Representatives", answer_en_alt: ["the Senate and House of Representatives", "Senate and House"], category: "American Government", subcategory: "System of Government" },
  { number: 20, question_en: "Name one power of the U.S. Congress.", answer_en: "Writes laws; Declares war; Makes the federal budget", answer_en_alt: ["writes laws", "declares war", "makes the federal budget"], category: "American Government", subcategory: "System of Government" },
  { number: 21, question_en: "How many U.S. senators are there?", answer_en: "One hundred (100)", answer_en_alt: ["100", "one hundred"], category: "American Government", subcategory: "System of Government" },
  { number: 22, question_en: "How long is a term for a U.S. senator?", answer_en: "Six (6) years", answer_en_alt: ["6", "six", "six years"], category: "American Government", subcategory: "System of Government" },
  { number: 23, question_en: "Who is one of your state's U.S. senators now?", answer_en: "Answers will vary by state", answer_en_alt: [], category: "American Government", subcategory: "System of Government", starred: true },
  { number: 24, question_en: "How many voting members are in the House of Representatives?", answer_en: "Four hundred thirty-five (435)", answer_en_alt: ["435", "four hundred thirty-five"], category: "American Government", subcategory: "System of Government" },
  { number: 25, question_en: "How long is a term for a member of the House of Representatives?", answer_en: "Two (2) years", answer_en_alt: ["2", "two", "two years"], category: "American Government", subcategory: "System of Government" },
  { number: 26, question_en: "Why do U.S. representatives serve shorter terms than U.S. senators?", answer_en: "To more closely follow public opinion", answer_en_alt: ["to more closely follow public opinion"], category: "American Government", subcategory: "System of Government" },
  { number: 27, question_en: "How many senators does each state have?", answer_en: "Two (2)", answer_en_alt: ["2", "two"], category: "American Government", subcategory: "System of Government" },
  { number: 28, question_en: "Why does each state have two senators?", answer_en: "Equal representation for small states; The Great Compromise (Connecticut Compromise)", answer_en_alt: ["equal representation for small states", "the Great Compromise", "Connecticut Compromise"], category: "American Government", subcategory: "System of Government" },
  { number: 29, question_en: "Name your U.S. representative.", answer_en: "Answers will vary by district", answer_en_alt: [], category: "American Government", subcategory: "System of Government" },
  { number: 30, question_en: "What is the name of the Speaker of the House of Representatives now?", answer_en: "Mike Johnson", answer_en_alt: ["Mike Johnson", "Johnson"], category: "American Government", subcategory: "System of Government", starred: true },
  { number: 31, question_en: "Who does a U.S. senator represent?", answer_en: "Citizens of their state; People of their state", answer_en_alt: ["citizens of their state", "people of their state", "all people of the state"], category: "American Government", subcategory: "System of Government" },
  { number: 32, question_en: "Who elects U.S. senators?", answer_en: "Citizens from their state", answer_en_alt: ["citizens from their state"], category: "American Government", subcategory: "System of Government" },
  { number: 33, question_en: "Who does a member of the House of Representatives represent?", answer_en: "Citizens in their congressional district", answer_en_alt: ["citizens in their congressional district", "citizens in their district", "people in their district"], category: "American Government", subcategory: "System of Government" },
  { number: 34, question_en: "Who elects members of the House of Representatives?", answer_en: "Citizens from their congressional district", answer_en_alt: ["citizens from their congressional district", "citizens from their district"], category: "American Government", subcategory: "System of Government" },
  { number: 35, question_en: "Some states have more representatives than other states. Why?", answer_en: "Because of the state's population", answer_en_alt: ["the state's population", "they have more people", "some states have more people"], category: "American Government", subcategory: "System of Government" },

  // The President
  { number: 36, question_en: "The President of the United States is elected for how many years?", answer_en: "Four (4) years", answer_en_alt: ["4", "four", "four years"], category: "American Government", subcategory: "System of Government" },
  { number: 37, question_en: "The President of the United States can serve only two terms. Why?", answer_en: "Because of the 22nd Amendment; To keep the president from becoming too powerful", answer_en_alt: ["because of the 22nd Amendment", "to keep the president from becoming too powerful"], category: "American Government", subcategory: "System of Government" },
  { number: 38, question_en: "What is the name of the President of the United States now?", answer_en: "Donald Trump", answer_en_alt: ["Trump", "Donald Trump"], category: "American Government", subcategory: "System of Government", starred: true },
  { number: 39, question_en: "What is the name of the Vice President of the United States now?", answer_en: "JD Vance", answer_en_alt: ["Vance", "JD Vance", "J.D. Vance"], category: "American Government", subcategory: "System of Government", starred: true },
  { number: 40, question_en: "If the president can no longer serve, who becomes president?", answer_en: "The Vice President", answer_en_alt: ["the Vice President"], category: "American Government", subcategory: "System of Government" },
  { number: 41, question_en: "Name one power of the president.", answer_en: "Signs bills into law; Vetoes bills; Enforces laws; Commander in Chief of the military; Chief diplomat; Appoints federal judges", answer_en_alt: ["signs bills into law", "vetoes bills", "enforces laws", "Commander in Chief of the military", "chief diplomat", "appoints federal judges"], category: "American Government", subcategory: "System of Government" },
  { number: 42, question_en: "Who is Commander in Chief of the U.S. military?", answer_en: "The President", answer_en_alt: ["the President"], category: "American Government", subcategory: "System of Government" },
  { number: 43, question_en: "Who signs bills to become laws?", answer_en: "The President", answer_en_alt: ["the President"], category: "American Government", subcategory: "System of Government" },
  { number: 44, question_en: "Who vetoes bills?", answer_en: "The President", answer_en_alt: ["the President"], category: "American Government", subcategory: "System of Government" },
  { number: 45, question_en: "Who appoints federal judges?", answer_en: "The President", answer_en_alt: ["the President"], category: "American Government", subcategory: "System of Government" },
  { number: 46, question_en: "The executive branch has many parts. Name one.", answer_en: "President; Cabinet; Federal departments and agencies", answer_en_alt: ["President", "Cabinet", "federal departments and agencies"], category: "American Government", subcategory: "System of Government" },
  { number: 47, question_en: "What does the President's Cabinet do?", answer_en: "Advises the President", answer_en_alt: ["advises the President"], category: "American Government", subcategory: "System of Government" },
  { number: 48, question_en: "What are two Cabinet-level positions?", answer_en: "Secretary of State, Secretary of Defense, Attorney General, Secretary of the Treasury, and others", answer_en_alt: ["Secretary of Agriculture", "Secretary of Commerce", "Secretary of Defense", "Secretary of Education", "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security", "Secretary of Housing and Urban Development", "Secretary of the Interior", "Secretary of Labor", "Secretary of State", "Secretary of Transportation", "Secretary of the Treasury", "Secretary of Veterans Affairs", "Attorney General", "Vice President"], category: "American Government", subcategory: "System of Government" },
  { number: 49, question_en: "Why is the Electoral College important?", answer_en: "It decides who is elected president; It provides a compromise between popular election and congressional selection", answer_en_alt: ["it decides who is elected president", "it provides a compromise between popular election and congressional selection"], category: "American Government", subcategory: "System of Government" },

  // The Courts
  { number: 50, question_en: "What is one part of the judicial branch?", answer_en: "Supreme Court; Federal Courts", answer_en_alt: ["Supreme Court", "federal Courts"], category: "American Government", subcategory: "System of Government" },
  { number: 51, question_en: "What does the judicial branch do?", answer_en: "Reviews laws; Explains laws; Resolves disputes; Decides if a law goes against the Constitution", answer_en_alt: ["reviews laws", "explains laws", "resolves disputes", "decides if a law goes against the Constitution"], category: "American Government", subcategory: "System of Government" },
  { number: 52, question_en: "What is the highest court in the United States?", answer_en: "The Supreme Court", answer_en_alt: ["the Supreme Court"], category: "American Government", subcategory: "System of Government" },
  { number: 53, question_en: "How many seats are on the Supreme Court?", answer_en: "Nine (9)", answer_en_alt: ["9", "nine"], category: "American Government", subcategory: "System of Government" },
  { number: 54, question_en: "How many Supreme Court justices are usually needed to decide a case?", answer_en: "Five (5)", answer_en_alt: ["5", "five"], category: "American Government", subcategory: "System of Government" },
  { number: 55, question_en: "How long do Supreme Court justices serve?", answer_en: "For life; Lifetime appointment; Until retirement", answer_en_alt: ["for life", "lifetime appointment", "until retirement"], category: "American Government", subcategory: "System of Government" },
  { number: 56, question_en: "Supreme Court justices serve for life. Why?", answer_en: "To be independent of politics; To limit outside political influence", answer_en_alt: ["to be independent of politics", "to limit outside political influence"], category: "American Government", subcategory: "System of Government" },
  { number: 57, question_en: "Who is the Chief Justice of the United States now?", answer_en: "John Roberts", answer_en_alt: ["John Roberts", "Roberts"], category: "American Government", subcategory: "System of Government", starred: true },

  // Federal vs. State
  { number: 58, question_en: "Name one power that is only for the federal government.", answer_en: "Print paper money; Mint coins; Declare war; Create an army; Make treaties; Set foreign policy", answer_en_alt: ["print paper money", "mint coins", "declare war", "create an army", "make treaties", "set foreign policy"], category: "American Government", subcategory: "System of Government" },
  { number: 59, question_en: "Name one power that is only for the states.", answer_en: "Provide schooling and education; Provide protection (police); Provide safety (fire departments); Give a driver's license; Approve zoning and land use", answer_en_alt: ["provide schooling and education", "provide protection", "provide safety", "give a driver's license", "approve zoning and land use"], category: "American Government", subcategory: "System of Government", starred: true },
  { number: 60, question_en: "What is the purpose of the 10th Amendment?", answer_en: "It states that the powers not given to the federal government belong to the states or to the people", answer_en_alt: ["it gives powers not given to the federal government to the states or people", "powers not delegated to the federal government belong to the states or people"], category: "American Government", subcategory: "System of Government" },
  { number: 61, question_en: "Who is the governor of your state now?", answer_en: "Answers will vary by state", answer_en_alt: [], category: "American Government", subcategory: "System of Government", starred: true },
  { number: 62, question_en: "What is the capital of your state?", answer_en: "Answers will vary by state", answer_en_alt: [], category: "American Government", subcategory: "System of Government", starred: true },

  // C: Rights and Responsibilities (Q63-72)
  { number: 63, question_en: "What are two rights of everyone living in the United States?", answer_en: "Freedom of expression; Freedom of speech; Freedom of assembly; Freedom to petition the government; Freedom of religion; The right to bear arms", answer_en_alt: ["freedom of expression", "freedom of speech", "freedom of assembly", "freedom to petition the government", "freedom of religion", "the right to bear arms"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 64, question_en: "What do we show loyalty to when we say the Pledge of Allegiance?", answer_en: "The United States; The flag", answer_en_alt: ["the United States", "the flag"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 65, question_en: "Name one promise you make when you become a United States citizen.", answer_en: "Give up loyalty to other countries; Defend the Constitution and laws of the United States; Obey the laws of the United States; Serve in the U.S. military if needed; Be loyal to the United States", answer_en_alt: ["give up loyalty to other countries", "defend the Constitution", "obey the laws", "serve in the U.S. military", "be loyal to the United States"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 66, question_en: "How old do citizens have to be to vote for President?", answer_en: "Eighteen (18) and older", answer_en_alt: ["18", "eighteen", "eighteen and older"], category: "American Government", subcategory: "Rights and Responsibilities", starred: true },
  { number: 67, question_en: "There are four amendments to the Constitution about who can vote. Describe one of them.", answer_en: "Citizens eighteen and older can vote; You don't have to pay a poll tax to vote; Any citizen can vote (women and men); A male citizen of any race can vote", answer_en_alt: ["citizens eighteen and older can vote", "you don't have to pay a poll tax to vote", "any citizen can vote", "a male citizen of any race can vote"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 68, question_en: "Name one responsibility that is only for United States citizens.", answer_en: "Serve on a jury; Vote in a federal election", answer_en_alt: ["serve on a jury", "vote in a federal election"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 69, question_en: "Name one right only for United States citizens.", answer_en: "Vote in a federal election; Run for federal office", answer_en_alt: ["vote in a federal election", "run for federal office"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 70, question_en: "What are two ways that Americans can participate in their democracy?", answer_en: "Vote; Join a political party; Help with a campaign; Join a civic group; Run for office; Write to a newspaper; Call Senators and Representatives; Give an elected official your opinion on an issue", answer_en_alt: ["vote", "join a political party", "help with a campaign", "join a civic group", "run for office", "call Senators and Representatives"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 71, question_en: "When is the last day you can send in federal income tax forms?", answer_en: "April 15", answer_en_alt: ["April 15"], category: "American Government", subcategory: "Rights and Responsibilities" },
  { number: 72, question_en: "When must all men register for the Selective Service?", answer_en: "At age eighteen (18); Between eighteen (18) and twenty-six (26)", answer_en_alt: ["at age eighteen", "between eighteen and twenty-six", "18"], category: "American Government", subcategory: "Rights and Responsibilities" },

  // === AMERICAN HISTORY ===
  // A: Colonial Period and Independence (Q73-87)
  { number: 73, question_en: "What is one reason colonists came to America?", answer_en: "Freedom; Political liberty; Religious freedom; Economic opportunity; Escape persecution", answer_en_alt: ["freedom", "political liberty", "religious freedom", "economic opportunity", "escape persecution"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 74, question_en: "Who lived in America before the Europeans arrived?", answer_en: "American Indians; Native Americans", answer_en_alt: ["American Indians", "Native Americans"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 75, question_en: "What group of people was taken to America and sold as slaves?", answer_en: "Africans; People from Africa", answer_en_alt: ["Africans", "people from Africa"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 76, question_en: "Who wrote the Declaration of Independence?", answer_en: "Thomas Jefferson", answer_en_alt: ["Thomas Jefferson", "Jefferson"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 77, question_en: "When was the Declaration of Independence adopted?", answer_en: "July 4, 1776", answer_en_alt: ["July 4, 1776", "1776"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 78, question_en: "There were 13 original states. Name three.", answer_en: "New Hampshire, Massachusetts, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania, Delaware, Maryland, Virginia, North Carolina, South Carolina, Georgia", answer_en_alt: ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York", "New Jersey", "Pennsylvania", "Delaware", "Maryland", "Virginia", "North Carolina", "South Carolina", "Georgia"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 79, question_en: "What happened at the Constitutional Convention?", answer_en: "The Constitution was written; The Founding Fathers wrote the Constitution", answer_en_alt: ["the Constitution was written", "the Founding Fathers wrote the Constitution"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 80, question_en: "When was the Constitution written?", answer_en: "1787", answer_en_alt: ["1787"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 81, question_en: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", answer_en: "James Madison; Alexander Hamilton; John Jay; Publius", answer_en_alt: ["James Madison", "Alexander Hamilton", "John Jay", "Publius"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 82, question_en: "Why were the Federalist Papers important?", answer_en: "They helped people understand the Constitution; They supported passing the Constitution", answer_en_alt: ["they helped people understand the Constitution", "they supported passing the Constitution"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 83, question_en: "What is one thing Benjamin Franklin is famous for?", answer_en: "U.S. diplomat; Oldest member of the Constitutional Convention; First Postmaster General of the United States; Writer of 'Poor Richard's Almanac'; Started the first free libraries", answer_en_alt: ["U.S. diplomat", "oldest member of the Constitutional Convention", "first Postmaster General", "Poor Richard's Almanac", "started the first free libraries"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 84, question_en: "Who is the 'Father of Our Country'?", answer_en: "George Washington", answer_en_alt: ["George Washington", "Washington"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 85, question_en: "Who was the first President?", answer_en: "George Washington", answer_en_alt: ["George Washington", "Washington"], category: "American History", subcategory: "Colonial Period and Independence", starred: true },
  { number: 86, question_en: "Why did the colonists fight the British?", answer_en: "Because of high taxes (taxation without representation); Because the British army stayed in their houses; Because they didn't have self-government", answer_en_alt: ["high taxes", "taxation without representation", "the British army stayed in their houses", "they didn't have self-government"], category: "American History", subcategory: "Colonial Period and Independence" },
  { number: 87, question_en: "Name one American Indian tribe in the United States.", answer_en: "Cherokee; Navajo; Sioux; Chippewa; Choctaw; Pueblo; Apache; Iroquois; Creek; Blackfeet; Seminole; Cheyenne; Arawak; Shawnee; Mohegan; Huron; Oneida; Lakota; Crow; Teton; Hopi; Inuit", answer_en_alt: ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet", "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton", "Hopi", "Inuit"], category: "American History", subcategory: "Colonial Period and Independence" },

  // B: 1800s (Q88-97)
  { number: 88, question_en: "What territory did the United States buy from France in 1803?", answer_en: "The Louisiana Territory; Louisiana", answer_en_alt: ["the Louisiana Territory", "Louisiana"], category: "American History", subcategory: "1800s" },
  { number: 89, question_en: "Name one war fought by the United States in the 1800s.", answer_en: "War of 1812; Mexican-American War; Civil War; Spanish-American War", answer_en_alt: ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"], category: "American History", subcategory: "1800s" },
  { number: 90, question_en: "Name the U.S. war between the North and the South.", answer_en: "The Civil War; The War between the States", answer_en_alt: ["the Civil War", "the War between the States"], category: "American History", subcategory: "1800s" },
  { number: 91, question_en: "Name one problem that led to the Civil War.", answer_en: "Slavery; Economic reasons; States' rights", answer_en_alt: ["slavery", "economic reasons", "states' rights"], category: "American History", subcategory: "1800s" },
  { number: 92, question_en: "What was one important thing that Abraham Lincoln did?", answer_en: "Freed the slaves (Emancipation Proclamation); Saved (or preserved) the Union; Led the United States during the Civil War", answer_en_alt: ["freed the slaves", "Emancipation Proclamation", "saved the Union", "preserved the Union", "led the United States during the Civil War"], category: "American History", subcategory: "1800s", starred: true },
  { number: 93, question_en: "What did the Emancipation Proclamation do?", answer_en: "Freed the slaves; Freed slaves in the Confederacy; Freed slaves in the Confederate states; Freed slaves in most Southern states", answer_en_alt: ["freed the slaves", "freed slaves in the Confederacy", "freed slaves in the Confederate states"], category: "American History", subcategory: "1800s" },
  { number: 94, question_en: "What did Susan B. Anthony do?", answer_en: "Fought for women's rights; Fought for civil rights", answer_en_alt: ["fought for women's rights", "fought for civil rights"], category: "American History", subcategory: "1800s" },
  { number: 95, question_en: "Name one thing Abraham Lincoln is known for.", answer_en: "Freed the slaves; Emancipation Proclamation; 16th President; Saved the Union; Led the U.S. during the Civil War; Gettysburg Address", answer_en_alt: ["freed the slaves", "Emancipation Proclamation", "16th President", "saved the Union", "Gettysburg Address"], category: "American History", subcategory: "1800s" },
  { number: 96, question_en: "What amendment freed the slaves?", answer_en: "The 13th Amendment", answer_en_alt: ["the 13th Amendment", "13th Amendment", "thirteenth amendment"], category: "American History", subcategory: "1800s" },
  { number: 97, question_en: "What amendment gave citizenship to all persons born in the United States?", answer_en: "The 14th Amendment", answer_en_alt: ["the 14th Amendment", "14th Amendment", "fourteenth amendment"], category: "American History", subcategory: "1800s" },

  // C: Recent American History (Q98-112)
  { number: 98, question_en: "Name one war fought by the United States in the 1900s.", answer_en: "World War I; World War II; Korean War; Vietnam War; (Persian) Gulf War", answer_en_alt: ["World War I", "World War II", "Korean War", "Vietnam War", "Gulf War", "Persian Gulf War"], category: "American History", subcategory: "Recent American History" },
  { number: 99, question_en: "Who was President during World War I?", answer_en: "Woodrow Wilson", answer_en_alt: ["Woodrow Wilson", "Wilson"], category: "American History", subcategory: "Recent American History" },
  { number: 100, question_en: "Who was President during the Great Depression and World War II?", answer_en: "Franklin Roosevelt", answer_en_alt: ["Franklin Roosevelt", "FDR", "Roosevelt"], category: "American History", subcategory: "Recent American History" },
  { number: 101, question_en: "Who did the United States fight in World War II?", answer_en: "Japan, Germany, and Italy", answer_en_alt: ["Japan, Germany, and Italy", "Japan", "Germany", "Italy"], category: "American History", subcategory: "Recent American History" },
  { number: 102, question_en: "Before he was President, Eisenhower was a general. What war was he in?", answer_en: "World War II", answer_en_alt: ["World War II"], category: "American History", subcategory: "Recent American History" },
  { number: 103, question_en: "During the Cold War, what was the main concern of the United States?", answer_en: "Communism", answer_en_alt: ["Communism", "communism", "the spread of communism"], category: "American History", subcategory: "Recent American History" },
  { number: 104, question_en: "What movement tried to end racial discrimination?", answer_en: "Civil rights movement", answer_en_alt: ["civil rights movement"], category: "American History", subcategory: "Recent American History" },
  { number: 105, question_en: "What did Martin Luther King, Jr. do?", answer_en: "Fought for civil rights; Worked for equality for all Americans", answer_en_alt: ["fought for civil rights", "worked for equality for all Americans"], category: "American History", subcategory: "Recent American History", starred: true },
  { number: 106, question_en: "What major event happened on September 11, 2001, in the United States?", answer_en: "Terrorists attacked the United States", answer_en_alt: ["terrorists attacked the United States", "9/11"], category: "American History", subcategory: "Recent American History" },
  { number: 107, question_en: "Name one U.S. military conflict after the September 11, 2001 attacks.", answer_en: "War in Afghanistan; War in Iraq; War on Terror", answer_en_alt: ["war in Afghanistan", "war in Iraq", "war on Terror"], category: "American History", subcategory: "Recent American History" },
  { number: 108, question_en: "Name one American innovation.", answer_en: "Light bulb; Automobile (cars); Skyscrapers; Airplane; Assembly line; Landing on the moon; Integrated circuit (semiconductor)", answer_en_alt: ["light bulb", "automobile", "skyscrapers", "airplane", "assembly line", "landing on the moon", "integrated circuit"], category: "American History", subcategory: "Recent American History" },
  { number: 109, question_en: "Name one famous American inventor.", answer_en: "Thomas Edison; Alexander Graham Bell; The Wright Brothers; Robert Fulton; Benjamin Franklin; Eli Whitney; Henry Ford; Nikola Tesla", answer_en_alt: ["Thomas Edison", "Alexander Graham Bell", "the Wright Brothers", "Robert Fulton", "Benjamin Franklin", "Eli Whitney", "Henry Ford", "Nikola Tesla"], category: "American History", subcategory: "Recent American History" },
  { number: 110, question_en: "What was the women's suffrage movement?", answer_en: "The fight for women's right to vote", answer_en_alt: ["the fight for women's right to vote", "women fought for the right to vote"], category: "American History", subcategory: "Recent American History" },
  { number: 111, question_en: "Name one leader of the women's suffrage movement.", answer_en: "Susan B. Anthony; Elizabeth Cady Stanton; Sojourner Truth; Harriet Tubman; Lucretia Mott; Alice Paul", answer_en_alt: ["Susan B. Anthony", "Elizabeth Cady Stanton", "Sojourner Truth", "Harriet Tubman", "Lucretia Mott", "Alice Paul"], category: "American History", subcategory: "Recent American History" },
  { number: 112, question_en: "Name one important thing the women's suffrage movement did.", answer_en: "Women gained the right to vote (19th Amendment)", answer_en_alt: ["women gained the right to vote", "19th Amendment", "the 19th Amendment"], category: "American History", subcategory: "Recent American History" },

  // === INTEGRATED CIVICS ===
  // A: Geography (Q113-121)
  { number: 113, question_en: "Name one of the two longest rivers in the United States.", answer_en: "Missouri River; Mississippi River", answer_en_alt: ["Missouri River", "Mississippi River", "Missouri", "Mississippi"], category: "Integrated Civics", subcategory: "Geography" },
  { number: 114, question_en: "What ocean is on the West Coast of the United States?", answer_en: "Pacific Ocean", answer_en_alt: ["Pacific Ocean", "Pacific"], category: "Integrated Civics", subcategory: "Geography" },
  { number: 115, question_en: "What ocean is on the East Coast of the United States?", answer_en: "Atlantic Ocean", answer_en_alt: ["Atlantic Ocean", "Atlantic"], category: "Integrated Civics", subcategory: "Geography" },
  { number: 116, question_en: "Name one U.S. territory.", answer_en: "Puerto Rico; U.S. Virgin Islands; American Samoa; Northern Mariana Islands; Guam", answer_en_alt: ["Puerto Rico", "U.S. Virgin Islands", "American Samoa", "Northern Mariana Islands", "Guam"], category: "Integrated Civics", subcategory: "Geography" },
  { number: 117, question_en: "Name one state that borders Canada.", answer_en: "Maine; New Hampshire; Vermont; New York; Pennsylvania; Ohio; Michigan; Minnesota; North Dakota; Montana; Idaho; Washington; Alaska", answer_en_alt: ["Maine", "New Hampshire", "Vermont", "New York", "Pennsylvania", "Ohio", "Michigan", "Minnesota", "North Dakota", "Montana", "Idaho", "Washington", "Alaska"], category: "Integrated Civics", subcategory: "Geography" },
  { number: 118, question_en: "Name one state that borders Mexico.", answer_en: "California; Arizona; New Mexico; Texas", answer_en_alt: ["California", "Arizona", "New Mexico", "Texas"], category: "Integrated Civics", subcategory: "Geography" },
  { number: 119, question_en: "What is the capital of the United States?", answer_en: "Washington, D.C.", answer_en_alt: ["Washington, D.C.", "Washington DC"], category: "Integrated Civics", subcategory: "Geography", starred: true },
  { number: 120, question_en: "Where is the Statue of Liberty?", answer_en: "New York Harbor; Liberty Island; New Jersey; near New York City; on the Hudson River", answer_en_alt: ["New York Harbor", "Liberty Island", "New Jersey", "near New York City", "on the Hudson River"], category: "Integrated Civics", subcategory: "Geography", starred: true },
  { number: 121, question_en: "What country did the United States buy Alaska from?", answer_en: "Russia", answer_en_alt: ["Russia"], category: "Integrated Civics", subcategory: "Geography" },

  // B: Symbols (Q122-125)
  { number: 122, question_en: "Why does the flag have 13 stripes?", answer_en: "Because there were 13 original colonies; Because the stripes represent the original colonies", answer_en_alt: ["because there were 13 original colonies", "because the stripes represent the original colonies"], category: "Integrated Civics", subcategory: "Symbols" },
  { number: 123, question_en: "Why does the flag have 50 stars?", answer_en: "Because there is one star for each state; Because each star represents a state; Because there are 50 states", answer_en_alt: ["because there is one star for each state", "because each star represents a state", "because there are 50 states"], category: "Integrated Civics", subcategory: "Symbols" },
  { number: 124, question_en: "What is the name of the national anthem?", answer_en: "The Star-Spangled Banner", answer_en_alt: ["The Star-Spangled Banner"], category: "Integrated Civics", subcategory: "Symbols", starred: true },
  { number: 125, question_en: "The American flag is a symbol of the United States. Name another U.S. symbol.", answer_en: "Statue of Liberty; Bald eagle; National anthem; The White House; The Capitol; The Lincoln Memorial; The Washington Monument", answer_en_alt: ["Statue of Liberty", "bald eagle", "national anthem", "the White House", "the Capitol", "Lincoln Memorial", "Washington Monument"], category: "Integrated Civics", subcategory: "Symbols" },

  // C: Holidays (Q126-128)
  { number: 126, question_en: "When do we celebrate Independence Day?", answer_en: "July 4", answer_en_alt: ["July 4", "July 4th"], category: "Integrated Civics", subcategory: "Holidays", starred: true },
  { number: 127, question_en: "Name two national U.S. holidays.", answer_en: "New Year's Day; Martin Luther King Jr. Day; Presidents' Day; Memorial Day; Independence Day; Labor Day; Columbus Day; Veterans Day; Thanksgiving; Christmas", answer_en_alt: ["New Year's Day", "Martin Luther King Jr. Day", "Presidents' Day", "Memorial Day", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving", "Christmas"], category: "Integrated Civics", subcategory: "Holidays" },
  { number: 128, question_en: "What is one holiday that commemorates the U.S. military?", answer_en: "Memorial Day; Veterans Day; Armed Forces Day", answer_en_alt: ["Memorial Day", "Veterans Day", "Armed Forces Day"], category: "Integrated Civics", subcategory: "Holidays" },
];

export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'zh', label: '中文 (Chinese)', flag: '🇨🇳' },
  { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'tl', label: 'Tagalog', flag: '🇵🇭' },
  { code: 'ko', label: '한국어 (Korean)', flag: '🇰🇷' },
  { code: 'ar', label: 'العربية (Arabic)', flag: '🇸🇦' },
  { code: 'hi', label: 'हिन्दी (Hindi)', flag: '🇮🇳' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
  { code: 'ru', label: 'Русский (Russian)', flag: '🇷🇺' },
  { code: 'ja', label: '日本語 (Japanese)', flag: '🇯🇵' },
  { code: 'ht', label: 'Kreyòl Ayisyen', flag: '🇭🇹' },
  { code: 'bn', label: 'বাংলা (Bengali)', flag: '🇧🇩' },
  { code: 'fa', label: 'فارسی (Farsi)', flag: '🇮🇷' },
  { code: 'pl', label: 'Polski (Polish)', flag: '🇵🇱' },
  { code: 'uk', label: 'Українська (Ukrainian)', flag: '🇺🇦' },
  { code: 'ur', label: 'اردو (Urdu)', flag: '🇵🇰' },
  { code: 'am', label: 'አማርኛ (Amharic)', flag: '🇪🇹' },
  { code: 'my', label: 'ဗမာ (Burmese)', flag: '🇲🇲' },
  { code: 'ne', label: 'नेपाली (Nepali)', flag: '🇳🇵' },
  { code: 'so', label: 'Soomaali (Somali)', flag: '🇸🇴' },
  { code: 'sw', label: 'Kiswahili (Swahili)', flag: '🇰🇪' },
];

export const LANGUAGE_LABELS = Object.fromEntries(SUPPORTED_LANGUAGES.map(l => [l.code, l.label]));
export const LANGUAGE_FLAGS = Object.fromEntries(SUPPORTED_LANGUAGES.map(l => [l.code, l.flag]));